### ISSUE TITLE
Set up the shared deployment environment

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#2]
We'll need to decide how and where to deploy the app while we are developing it. You will probably set up a local environment on your own machine for the purposes of developing and debugging. What we also need is somewhere me & Tim could look at the app, test it and provide feedback. It is essential to be able to deploy multiple versions at the same time (e. g. one version per branch), and it would make sense to make the deployment completely automated.

We're currently looking at setting this up on the EBI infrastructure. Could you please provide a list of requirements which you need in terms of the web server, database, and your preferred method of setting up the continuous integration?

**Comment by tskir** [comment]
I'm also thinking that another important consideration is that @joj0s should have some way of direct access to this shared environment, to be able to directly manipulate the database (for debugging/resetting/changing schema), restart the webserver etc. If we do it on the EBI infrastructure it might be difficult.

@tcezard Do you suppose it would be beneficial having an environment which we could all access more or less directly? Do we have a way of doing that using the EBI infrastructure? If not, could we use some external paid service, like Google Cloud Platform?

**Comment by tskir** [comment]
@jmmut Your feedback would be very welcome as well. Which way did you do this with previous years GSoC projects?

**Comment by jmmut** [comment]
our previous GSoC projects were easier in this aspect. It was about a CLI program, which only needs download; or revamping the web services API where the student would work locally with a dummy DB, and then we would deploy in our beta sites without the student being able to access that.

**Comment by tcezard** [comment]
I'm sure this would not be an issue to use external paid platform. The only issue I can foresee is an admin one. I'll enquire.

**Comment by jmmut** [comment]
regarding the issue of needing several branches at the same time, maybe you can setup up our internal gitlab to do deployments on PRs. For instance you have pr 3 and pr 4, and they get deployed at wwwdev.ebi.ac.uk/eva/curation/pr/3 and wwwdev.ebi.ac.uk/eva/curation/pr/3. that would allow public access, though. if the operations allow data modification you might want to do in wwwint (non-public). I have no idea about the process or justification of granting access to gsoc users.

**Comment by tskir** [comment]
@jmmut Just to make sure I'm getting this right: you're suggesting to make our internal GitLab watch _this_ GitHub repository and autodeploy its PR branches on the EBI infrastructure? If that is possible, then it sounds like a good solution. The only drawback is that Giorgos won't have _direct_ access to the database or the webservers, but with autodeploy the need for that will likely be minimal (@joj0s correct me if I'm wrong), and he will still be able to access the _result_ of the deployment if we deploy on `wwwdev`.

The fact that deploying on `wwwdev` provides public access is not an issue, as we're not working with any sensitive data. It's essentially going to be a sandbox environment.

**Comment by jmmut** [comment]
my concern about wwwdev is with write operations, even if if's a sandbox. Do you allow adding entries? could someone add a billion entries? could someone delete all the data (this would "just" be annoying)? do you allow entering strings in forms? could you write there a string of GBs in legth? are there DB limits in place? what about SQL injection? do you have protection for that? if not, could someone affect other databases in the same database server?

**Comment by tskir** [comment]
@jmmut Wow. That's quite a list you got there. You would make an awesome QA/security specialist :) OK, I now agree we shouldn't expose a writable service. Let's approach it this way: at first, the prototype will be read only anyway; and then, once we develop the first write operation, we will at the same time introduce authentication.

Also, concerning the first part of my previous comment, could you confirm that my idea of GitLab pulling PRs from a _GitHub_ repository is correct?

**Comment by joj0s** [comment]
Hello! Of course I can't provide much input on EBI infrastructure, however the specifications of this project were that we were going to build a new database so we will not require access to any existing EBI databases or APIs. If this is the case then I think we could set up some external environment. Since I think that using GitHub Actions for CI is a good choice, the suggestion I have is to automate the deployment process for any chosen branch using Heroku (https://devcenter.heroku.com/articles/github-integration#automatic-deploys) which integrates with GitHub and is also free (although we can't use SSL with the free version)

**Comment by jmmut** [comment]
> Also, concerning the first part of my previous comment, could you confirm that my idea of GitLab pulling PRs from a GitHub repository is correct?

yes, sorry, that is correct.

**Comment by jmmut** [comment]
the heroku option is good too. However I'm not familiar with it and I don't know if you can connect to a DB from your deploys at heroku. I guess you can't, from what you say about SSL. You could still have some in-memory storage for the first versions.

**Comment by tskir** [comment]
OK, then to summarise, this should be our approach for now:
1. @joj0s — for now, you can start (or at least attempt/evaluate) developing using GitHub Actions CI + a free Heroku instance. Please let me know as soon as possible once either have a successful deployment, or have run into some problems with this approach.
  + A free Heroku instance will definitely have some limitations, such as a maximum of 10,000 DB rows (if I'm reading their website correctly). This will be fine for early stages of development, as we can use only a subset of data, but will become a problem later on.
2. @tcezard will inquire about the administrative protocol to obtain a paid Heroku instance. @joj0s could you please investigate their different tiers and provide an estimate of the cost for having a paid instance for the next 4 months?
3. In parallel, me and @jmmut will evaluate the possibility of doing a deployment through GitLab (this will be necessary as a future production deployment anyway).

**Comment by tskir** [comment]
Additional possibility is to use EBI's Embassy cloud [(docs)](http://docs.embassy.ebi.ac.uk/userguide/Embassy_About.html) which was designed with having external collaborators in mind. I will investigate this opportunity as well. This does not immediately change plans outlined in the previous comment just yet, but it is possible that we will migrate from free Heroku to Embassy instead of paid Heroku.

**Comment by joj0s** [comment]
I'm currently working on the option of Heroku. I have successfully deployed the basic Django app I built at the start of my proposal using GitHub integration (https://djangonts.herokuapp.com/), and it turns out it supports secure connections as well. I am currently looking at the cost of upgrading the database, plus whether it is possible to deploy multiple branches at once, and I'll get back to you on that.

**Comment by joj0s** [comment]
Regarding multiple deploys for each pull request, it seems it is possible through "Review Apps" (https://devcenter.heroku.com/articles/github-integration-review-apps)

Now for an estimated monthly cost, if we were to use Heroku's available Postgres database, a 10 million row instance would cost 9$ per month. In addition, the server is going to become idle after 30 minutes of inactivity which means that first loads are going to be very slow but I don't think it is a major issue. I haven't found any other obstacles with the free plan

**Comment by tskir** [comment]
@joj0s Good, in this case please proceed with free Heroku deployment. The most likely transition from there would be to the Embassy cloud. I haven't looked into it yet but am planning to.

**Comment by joj0s** [comment]
I have managed to deploy a test app to Heroku and set up separate automatic deployments for pull requests as well (Heroku calls them review apps). The problem is that each review app creates a new database, meaning that if we were to use Heroku's PostgreSQL, every PR app would have no data in it.

**Comment by tskir** [comment]
> I have managed to deploy a test app to Heroku and set up separate automatic deployments for pull requests as well (Heroku calls them review apps).
Great! Could you submit a PR with the instructions how to set it up from scratch?

> The problem is that each review app creates a new database, meaning that if we were to use Heroku's PostgreSQL, every PR app would have no data in it.
I don't suppose it's much of a problem for now. For the next month or so, we'll only need some dummy data — perhaps just a few traits — for testing purposes. Once the prototype is ready, we can just hardcode creating several test records in the database on app startup.

> I am currently looking at manually connecting to the main Heroku DB.
By the main DB, do you mean some central DB for all instances of the application deployed in Heroku? Even if possible, this might be counterproductive, because it is possible that we will change DB schema from time to time in the process of developing the app. Using a single DB for all instances would mess with that.

**Comment by joj0s** [comment]
Sure, I can start with the PR. Another thing also is that the default setting for the databases is to use SQLite in the local development environment and Heroku's Postgres for the deployed instance. Do we want to keep that?

**Comment by joj0s** [comment]
Oh and also since this is a development deployment, do we want to use production settings like disabling debugging?

**Comment by tskir** [comment]
> Another thing also is that the default setting for the databases is to use SQLite in the local development environment and Heroku's Postgres for the deployed instance. Do we want to keep that?

I don't think it's a good idea to use different database engines for development & production (if I interpreted what you're saying correctly). Since Heroku is using Postgres and we're planning to use Postres in production, wouldn't it be possible to also have it set up locally and use for the development as well?

> Oh and also since this is a development deployment, do we want to use production settings like disabling debugging?

At this point, leave the development settings in the deployment. We are not handling any sensitive data, and having e. g. tracebacks displayed would be very convenient.
