### ISSUE TITLE
Implement trait view table

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#20]
This is the main table which displays the traits.

![image](https://user-images.githubusercontent.com/10669118/83942582-ae808480-a7ec-11ea-9d08-ae4fa7a69602.png)

**Comment by joj0s** [comment]
I decided to not include the icons because they take up unnecessary space. Also I think each label being of different size doesn't look bad, but if you want to match the prototype in terms of every label being the same length, let me know and I can add that.

**Comment by tskir** [comment]
> I updated the PR #36 to include the final table design. I decided to not include the icons because they take up unnecessary space. Also I think each label being of different size doesn't look bad, but if you want to match the prototype in terms of every label being the same length, let me know and I can add that.

I think both decisions (to drop icons & to make labels differently sized) are very good! I like what we have now in #36. So I approve those changes, and in the future also feel free to deviate from the mockup where you feel it would be sensible.
