### ISSUE TITLE
Display main information on a single trait page

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#21]
![image](https://user-images.githubusercontent.com/10669118/83946238-6e7acb00-a807-11ea-8918-c57fa954cdb3.png)

While the UI mockup provides a general idea on how to organise the blocks, also keep in mind that trait names can be quite long. The longest which is currently present in the ClinVar database is "Capillary malformation of the lower lip, lymphatic malformation of face and neck, asymmetry of face and limbs, and partial/generalized overgrowth", at 145 characters long. We should ensure that the layout is at least not _badly_ broken by such trait names.

**Comment by joj0s** [comment]
I am currently working on this issue. Just to clarify, given that we redesigned the way we show term information, the deliverable for this would be the top row showing trait information right?

**Comment by tskir** [comment]
> I am currently working on this issue. Just to clarify, given that we redesigned the way we show term information, the deliverable for this would be the top row showing trait information right?

Yes, you're right. I've renamed the issue to better reflect the changed scope.
