### ISSUE TITLE
Redesign the representation of current + suggested mappings

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#22]
This section currently looks like this in the mockup:

![image](https://user-images.githubusercontent.com/10669118/83946504-3bd1d200-a809-11ea-82d8-fc0510aacff5.png)

When I started writing an issue for its implementation, several things occurred to me, and now I think that for this specific section we should go back to the mockup and modify it in a few ways.

The primary change has to do with how we treat the mapping which is currently assigned to the trait, versus all others (suggested/possible) mappings. Currently the main mapping is on the top, in large font and the same design as the summary trait information, while possible mappings are smaller boxes in different design. This leads to a few problems:
* Relationship between the main and possible mappings is currently unspecified, but there are two scenarios which are both bad:
  + Either the mapping which is currently selected appears both on top and in the list of possible mappings, leading to duplication, which is not great;
  + Or the main mapping is present _only_ on the top. In this case, when we click "Map to selection", presumably this mapping will go to the top, while the top mapping will go back into the list of possible mappings. This is also rather confusing.
* Information which is displayed for the main vs. all other mappings is not the same. For the main, we have (term, label, status) + it's clickable and leads to an ontology term page. While for all other mappings, we have (term, label, user) and it's not clickable. In actuality, we need (term, label, status, user) + clickability for **all** mappings. The use case for that is for example when a curator wants to quickly open all possible mappings in new tabs and check out their descriptions and other attributes.

## Redesign suggestion
So what I suggest to do is to redesign the list of mappings as a table. It will have columns (term, label, term status, user who suggested the mapping), where the term is clickable and leads to the ontology term page. The table will contain all mappings, and the mapping currently assigned to this term will be highlighted in some way (either with bold, or with background colour, or possibly both).

To change the mapping, there can be two approaches, choose either one:
* Add a separate column which will contain a “Map to this term” button for each mapping
* Or make the rows in the table selectable and confirm the selection with a single “Map to selection” button, much like in the current design.

## Displaying terms which are not yet in ontologies
The design should also include a way to display a mapping to a term which is not yet in any ontology and was suggested by using the "Create new term" button.

**Comment by joj0s** [comment]
> The design should also include a way to display a mapping to a term which is not yet in any ontology and was suggested by using the "Create new term" button.

That would mean that we show every single newly suggested term because we have no way of knowing what trait any suggested term refers to, right?

**Comment by joj0s** [comment]
I implemented the changes you mentioned, and I included a section of newly created mappings as well. Tell me your thoughts!

**Comment by tskir** [comment]
> That would mean that we show every single newly suggested term because we have no way of knowing what trait any suggested term refers to, right?

No, not quite. The total amount of newly suggested terms, if counted together throughout the app, could easily exceed 100 or even more, so it would be confusing & not feasible to display them all for each trait.

My idea with the "Create new term" button was that it will not only create an `awaiting_creation` term, but _also_ a mapping from the trait (from the page of which it was created) to this new term. If implemented in that way, it would be possible to only display `awaiting_creation` terms related to the trait we are currently browsing.

> I implemented the changes you mentioned, and I included a section of newly created mappings as well.

I looked at the updated mockup, and this section actually looks really good! I don't have any further comments, except for what I wrote above. Let's discuss it, and after that this issue can be closed.

**Comment by joj0s** [comment]
> My idea with the "Create new term" button was that it will not only create an awaiting_creation term, but also a mapping from the trait (from the page of which it was created) to this new term. If implemented in that way, it would be possible to only display awaiting_creation terms related to the trait we are currently browsing.

Ok, then I think I should rename the button to something like "Create and map to new term" to be clearer

**Comment by joj0s** [comment]
> Ok, then I think I should rename the button to something like "Create and map to new term" to be clearer

I renamed the label next to the button instead to make its purpose clearer

**Comment by tskir** [comment]
> Ok, then I think I should rename the button to something like "Create and map to new term" to be clearer

> I renamed the label next to the button instead to make its purpose clearer

Yes, very good, I support this change

**Comment by joj0s** [comment]
Should I close this issue or is there anything else you would like to see changed?

**Comment by tskir** [comment]
Nope, everything's good here
