### ISSUE TITLE
Implement the review functionality

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#25]
![image](https://user-images.githubusercontent.com/10669118/83947118-fadbbc80-a80c-11ea-83a8-61bfd062da61.png)

**Comment by joj0s** [comment]
I think I should enforce a `unique_together` constraint between a mapping_id and a reviewer so that the same person cannot issue two reviews for the same mapping.

**Comment by joj0s** [comment]
Additional points to consider:
- The mapping curator shouldn't be able to issue a review for the mapping he curated
- What should the N number of reviews be before a mapping is considered reviewed?
- When a user has already reviewed a trait, should I hide the 'Review' button or maybe add something else instead of it? Or should I just issue a warning pop up?

**Comment by tskir** [comment]
Yes, it makes sense. Also, in addition to the database constraint, the UI also shouldn't allow someone to add a second review once the first one has already been added

**Comment by joj0s** [comment]
@tskir Just making sure you didn't miss the latest comment because I posted it back to back with the first one.

**Comment by tskir** [comment]
Indeed, thank you!

> The mapping curator shouldn't be able to issue a review for the mapping he curated

Correct.

> What should the N number of reviews be before a mapping is considered reviewed?

It should be configurable, for now let's make it 2.

> When a user has already reviewed a trait, should I hide the 'Review' button or maybe add something else instead of it? Or should I just issue a warning pop up?

I was thinking maybe we can turn it from "✓ REVIEW" into "REVIEWED" and make it inactive. Something like that

**Comment by tskir** [comment]
As discussed yesterday, this will include implementing the first computed fields using the django-computedfields package, as discussed in #41.
