### ISSUE TITLE
Implement the “Suggest existing term” section

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#26]
![image](https://user-images.githubusercontent.com/10669118/83947130-134bd700-a80d-11ea-9ff5-c6001345e5ec.png)

This should include some form of validation (the pasted URI should point to a valid ontology).

**Comment by joj0s** [comment]
Should I automatically map to that term, or should I just add it as a suggestion to the table?

**Comment by tskir** [comment]
In a situation where someone wants to suggest an existing term (or create a new term), it's highly likely that the reason they're doing that is all existing suggestions aren't probably that good.

So let's change the button to "Add term and map", similarly to how we did this with the new terms
