### ISSUE TITLE
Implement the history section

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#28]
![image](https://user-images.githubusercontent.com/10669118/83947179-645bcb00-a80d-11ea-8d8a-c169508a54a4.png)

This issue does not include comments functionality.

**Comment by joj0s** [comment]
Should we include anything other than mappings to terms for this section?

**Comment by tskir** [comment]
> Should we include anything other than mappings to terms for this section?

For now, it's fine to include only mapping and also reviews in this timeline.

In the future, we'll probably want to log all events which cause the trait to change its status, including it becoming e.g. obsolete or deleted. But this will probably necessitate changes in the data model since as far as I remember those things aren't being stored anywhere right now.
