### ISSUE TITLE
Implement minimal prototype for the app

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#3]
This can be flexible depending on how you think it could be implemented best. Some ideas:
* The prototype should include minimal UI and data model
* It may have only one page, for instance the list of traits and to which term they are mapped to
* It doesn't need to include any functionality on loading traits from an external source, just using dummy data will be OK for now

**Comment by joj0s** [comment]
First of all regarding the data model, do you agree with the database schema I suggested in my proposal? If so, I can start with a more basic model of that and some dummy data to create the primary workflow

**Comment by tskir** [comment]
Yes, the data model was very sensible. We might have to iron out some fine details about statuses and keeping track of curation history, but the basic stuff should be all correct. As you mentioned yourself, we will only need a subset of the whole model to start with the basic prototyping

**Comment by joj0s** [comment]
Great, one thing though. According to this model, there wouldn't be a single endpoint to get all valid and reviewed mappings, but the endpoint would be something like `/api/mappings?status=mapped` . Would that be a problem?

**Comment by tskir** [comment]
Not a problem. As long the final endpoint name is static, it can include any parameters.
