### ISSUE TITLE
Implement querying ZOOMA to get possible mappings for a trait

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#30]
This should essentially be done by copying the code from the main Open Targets repository, specifically from the [`trait_mapping`](https://github.com/EBIvariation/eva-cttv-pipeline/tree/master/eva_cttv_pipeline/trait_mapping) directory.

**Comment by joj0s** [comment]
When should we trigger ZOOMA queries? My guess is whenever a new trait is being imported?

**Comment by tskir** [comment]
> When should we trigger ZOOMA queries? My guess is whenever a new trait is being imported?

Yeah, that's a good question. Currently we have ClinVar, OLS and ZOOMA queries, and eventually we should have a situation where:
* Each import can be triggered manually and separately. E.g. there will be buttons "Update ClinVar",    "Update OLS", "Update ZOOMA" etc. which will trigger full updates from the respective datasources.
* Also, some imports will probably trigger other imports for a subset of records. For example, when we do ClinVar import, it makes sense to also do OLS and ZOOMA queries at least for the newly added records.

So here's what we are going to do. For _this_ ticket, it's enough to just implement the functionality itself, and add an "Update ZOOMA" button somewhere which will trigger the full manual import.

For the future, we have issue #32 which is about a UI mockup of a page to display import status and all those buttons for triggering imports. When we get to this part, let's use that issue to discuss which imports will trigger each other under which circumstances.

**Comment by joj0s** [comment]
After reviewing the code you linked, I think that it contains a lot more functionality than we currently need. Would it be ok if I created my own code to get ZOOMA suggestions and used this code as help?

Also, we currently don't have any fields in the DB model for ZOOMA confidence. Do we need that?

**Comment by tskir** [comment]
> After reviewing the code you linked, I think that it contains a lot more functionality than we currently need.

Eventually we are looking to port _all_ functionality from there, including the entire trait mapping pipeline. One way this could work is that, if the pipeline considers the mapping to be of "high quality", it will assign it automatically and move the trait directly into review (rather than starting with the unmapped status). However, in this ticket it's fine to only implement the core of that functionality (only querying ZOOMA itself). I've created a follow-up ticket, #44.

> Would it be ok if I created my own code to get ZOOMA suggestions and used this code as help?

Yes, that would fine. When convenient, you can also just copy-paste blocks from there and adjust as needed. Once everything is ported into the app, I'll just get rid of that part in the original repository altogether.

> Also, we currently don't have any fields in the DB model for ZOOMA confidence. Do we need that?

Yes, it would be useful. We need to store and display it. You can either implement it here or do it in #44, whichever is more convenient.

**Comment by joj0s** [comment]
Alright so to define the scope of this and #44, this issue regards querying ZOOMA and getting back the results, and #44 regards automatically mapping suggestions with HIGH confidence and querying OLS to check the status of the suggestion?

**Comment by joj0s** [comment]
Also am I missing something regarding ontology filtering in Zooma? For example this request http://www.ebi.ac.uk/spot/zooma/v2/api/services/annotate?propertyValue=cerebral+creatine+deficiency+syndrome&filter=ontologies:[efo]
should return only EFO ontologies or nothing, but instead returns an Orphanet one. I am confused because this is how the ontology filters are built in the trait_mapping directory you provided.

**Comment by joj0s** [comment]
> Also am I missing something regarding ontology filtering in Zooma? For example this request http://www.ebi.ac.uk/spot/zooma/v2/api/services/annotate?propertyValue=cerebral+creatine+deficiency+syndrome&filter=ontologies:[efo]
should return only EFO terms or nothing, but instead returns an Orphanet one. I am confused because this is how the ontology filters are built in the trait_mapping directory you provided.

Nevermind, it turns out I have to first specify the 'required' filter as none to have the ontologies filter working

**Comment by tskir** [comment]
> Alright so to define the scope of this and #44, this issue regards querying ZOOMA and getting back the results, and #44 regards automatically mapping suggestions with HIGH confidence and querying OLS to check the status of the suggestion?

That's right.

> Nevermind, it turns out I have to first specify the 'required' filter as none to have the ontologies filter working

Yes. If I remember correctly, there should be two fields, once specifies the _filter_ and another one the _priority order_ of the different ontologies.
