### ISSUE TITLE
Implement querying OLS to update term status

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#31]
Example of an OLS query through JSON API: https://www.ebi.ac.uk/ols/api/ontologies/efo/terms?iri=http://www.ebi.ac.uk/efo/EFO_0000612

This ticket only inlcudes developing the capability to do the query and update the data. Running it automatically or manually will be implemented in other tickets.

**Comment by joj0s** [comment]
So the way I see it, different kinds of status values require different handling of queries. In particular, OLS queries should:

- Check whether terms with the "Awaiting Import" status are now in EFO and change them into "Current" if they are
- Check **in EFO** whether "Current" terms are obsolete or deleted
- Check **in their parent ontology** if "Needs Import" or "Awaiting Import" terms are obsolete or deleted

Please let me know If I missed something.

**Comment by tskir** [comment]
Yes, as far as I can see, everything you described is spot on. Actually, originally I only considered the first two cases, but the third one makes sense as well

**Comment by joj0s** [comment]
In essence, I am running OLS updates only for current, awaiting_import and needs_import terms right? 

Running it for terms that need or await creation is of course problematic, however how should we deal with deleted and obsolete terms, especially those that have been previously mapped to a trait? (The rest will be deleted automatically if they are not picked up in the next ZOOMA query) 

Do we keep them in the db for reference, or do we delete them?

**Comment by tskir** [comment]
> In essence, I am running OLS updates only for current, awaiting_import and needs_import terms right?

Yes, this looks correct to me.

> Running it for terms that need or await creation is of course problematic

Correct. Since they don't yet have an ID, we can't run OLS for them.

> how should we deal with deleted and obsolete terms, especially those that have been previously mapped to a trait? (The rest will be deleted automatically if they are not picked up in the next ZOOMA query)
>
> Do we keep them in the db for reference, or do we delete them?

I would say, for provenance/history purposes, let's keep them (so that they can be displayed in the history section)
