### ISSUE TITLE
Implement dummy data importing for testing

### ISSUE THREAD

**Issue by joj0s** [EBIvariation/trait-curation#46]
Right now, when a new deployment is made to Heroku, a new database instance is created. It would be convenient to have a button to trigger import of dummy data so that testing of the app's UI and logic can be made easier

**Comment by joj0s** [comment]
@tskir Some considerations about this issue.

- Should we drop any pre-existing data before importing new ones? I'd say yes due to possible conflicts happening
- How much data should we import for every model? I'm thinking we should import enough to cover any existing edge case, one or two for each possible status for example
- Should we import dummy data for easily accessible cases? For example since there is an open PR on getting ZOOMA suggestions, should I create dummy suggestions as well?

**Comment by tskir** [comment]
> Should we drop any pre-existing data before importing new ones? I'd say yes due to possible conflicts happening

Yes, it's OK to wipe the database

> How much data should we import for every model? I'm thinking we should import enough to cover any existing edge case, one or two for each possible status for example

Agreed, just a few examples should suffice.

> Should we import dummy data for easily accessible cases? For example since there is an open PR on getting ZOOMA suggestions, should I create dummy suggestions as well?

I'm not sure I got this entirely; what do you mean by 'easily accessible' cases? 

Regarding the contents of dummy data, I think it should cover everything which is currently in the model (perhaps including already opened PRs like ZOOMA suggestions); and then every time we add something to the model/functionality which might require testing, we can update the dummy data in the same PR.

Essentially, think of the dummy data as a precursor to automated integration testing (which we will implement at some point).

**Comment by joj0s** [comment]
> I'm not sure I got this entirely; what do you mean by 'easily accessible' cases?
I mean that we can easily get unmapped trait names and mapping suggestions for traits using the already implemented ClinVar and ZOOMA queries. Should we have dummy data for those cases as well?

**Comment by tskir** [comment]
> >I'm not sure I got this entirely; what do you mean by 'easily accessible' cases?
>
> I mean that we can easily get unmapped trait names and mapping suggestions for traits using the already implemented ClinVar and ZOOMA queries. Should we have dummy data for those cases as well?

Ah, I see. On the one hand, yes, for these cases it should be fine to use existing querying functionality and not to bother with explicitly specifying dummy data. However, for example for ClinVar, we can't rely on the top X records from the variants_summary file being the same every time, because the data gets updated frequently. If this doesn't matter for testing then we should be fine
