### ISSUE TITLE
Get familiar with the current trait mapping & manual curation protocol

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#5]
We are developing a web app for something which is currently done using Python scripts and Google spreadsheets. So I think it'll be relevant for you to get familiar with this current approach.

There's currently a big PR which I'd like you to take a look at: https://github.com/EBIvariation/eva-cttv-pipeline/pull/99. As mentioned in the description, viewing it as a diff might be confusing, so you may just read the documentation as it appears _after_ the PR, available [here](https://github.com/tskir/eva-cttv-pipeline/tree/eva-1946-regroup-processing-steps).

Not all of it will be relevant for the web app, and in particular you may skip everything related to evidence string generation. Essentially, you will be porting an existing [manual curation protocol](https://github.com/tskir/eva-cttv-pipeline/blob/eva-1946-regroup-processing-steps/docs/manual-curation/README.md) into a consistent web app-based approach instead of all those multiple steps and running the scripts, and adding some new features to it.

You'll probably have some questions while reading that documentation, please do ask any and all of them.

**Comment by joj0s** [comment]
The first question I have, is this. As far as I understand, the current workflow is tightly coupled with Open Targets and ClinVar release cycles. Since we the goal is to have a consistent curated database of mappings, will we have to take those into consideration? It is especially the Open Targets specification releases which I am not sure about

**Comment by tskir** [comment]
The manual curation process _was_ indeed tightly coupled to the rest of Open Targets processing protocols. The main purpose of the PR which I linked above is to decouple the manual curation as much as possible into a separate process. You will not have to worry about either ClinVar or Open Targets release cycles, because:

* For ClinVar, you just periodically (e.g. weekly) request the latest version of the file and use it to update the list of traits in the database.
* The web app will not directly interact with Open Targets at all. It will just produce a list of mappings currently in the database and export them in the specified format. It will then be used by the evidence string generation protocol, which will take care of release cycles and anything else. Just to clarify again, we are not porting everything into the web app, only the manual curation protocol.

Please do let me know if this still doesn't make sense, I can elaborate more.

**Comment by joj0s** [comment]
So I understand that the curation process will be completely separate from Open Targets releases, however when you say in the second bullet that "it will produce a list of mappings currently in the database and export them", are you referring to a workflow where the user of the app would manually choose a number of mappings by browsing our data and then exporting them? Or would that list just comprise of mappings with the same criteria (e.g. "Mapped and reviewed") ?

**Comment by tskir** [comment]
@joj0s The second option is correct: the web app should just implement an endpoint which upon request provides _all_ traits which are currently in the database, mapped to non-obsolete ontology terms and reviewed by at least X reviewers. There will be no step where a user of the app manually selects anything for export, just an automated endpoint.

Or in other words, if we map the current [manual curation](https://github.com/EBIvariation/eva-cttv-pipeline/tree/master/docs/manual-curation) protocol into the web app terms:
|**Step**|**Current approach**|**Web app approach**|
|---|---|---
|1. Fetch data and attempt automated mapping|Fetching & mapping is done by a script on the cluster. The result is loaded in the Google spreadsheet [like this one](https://docs.google.com/spreadsheets/d/1HQ08UQTpS-0sE9MyzdUPO7EihMxDb2e8N14s1BknjVo/edit?usp=sharing)|Fetching & mapping is done by a web app. The result is loaded into the app's database|
|2. Curate|Manual curation happens in the spreadsheet|Manual curation happens using the web interface|
|3. Extract results|The filters are applied to the spreadsheet and certain columns are extracted as a TSV file. This file is then used by the evidence string generation pipeline|Evidence string generation pipeline, when needed, directly queries an endpoint of the app and gets the file in the same TSV format|
|4. Provide feedback|The curator manually extracts some rows from the table based on certain filters and creates a PR in the EFO GitHub repository|The web app automatically prepared the list of rows for import and creates a PR in the repository|

PR https://github.com/EBIvariation/eva-cttv-pipeline/pull/99/ has just been merged, so you can browser the master version of the repository to see the updated protocols. Additionally, the manual curation protocol is linked above.

Please do ask more questions if you have them.

**Comment by joj0s** [comment]
Great, the above diagram is extremely helpful! Another thing I'd like to ask, is marking terms as obsolete. Currently, we discussed using Zooma queries to suggest mappings. However the information about whether a term is obsolete or not can only be obtained through OLS (correct me if I'm wrong on that one). So the solution I am thinking for that would be to periodically check every mapped ontology (reviewed or not) against OLS and mark it as obsolete if it turns out to be as such.
1. Do you agree with that approach?
2. I assume a term becoming obsolete would mean losing its mapped status, right?

**Comment by tskir** [comment]
> However the information about whether a term is obsolete or not can only be obtained through OLS
Correct.

> So the solution I am thinking for that would be to periodically check every mapped ontology (reviewed or not) against OLS and mark it as obsolete if it turns out to be as such. Do you agree with that approach?
Yes, this sounds good. I don't see any other way to know that the term became obsolete other than periodically checking for it in OLS.

> I assume a term becoming obsolete would mean losing its mapped status, right?
Yes, correct.

**Comment by joj0s** [comment]
Great, at this point the only thing I am also not sure about, is the process of creating a new EFO term using our app to initiate it. It would be really helpful if you could walk me through the proposed steps.

**Comment by tskir** [comment]
@joj0s Actually, there is no standard for creating new terms yet. The current approach when submitting the PR is:
* For IMPORT terms, provide them in a Google spreadsheet
* For NEW terms, just specify them as free text in the PR description

For now it would be good to simply automate this

**Comment by joj0s** [comment]
I feel like I am familiar with the current curation protocol. If any more question about specific details arise I can ask them in another issue but for now I would say this can be closed.
