### ISSUE TITLE
Design user authentication interface

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#53]
Before doing the implementation, I feel we should make changes to the Figma mockup to see how all of this would look like.

**Comment by joj0s** [comment]
About this issue, since we are using Google as the authentication provider, I think there is not much to design here. My plan is to use a simple dropdown menu under the user icon in the navbar to provide users with a 'Log in with Google' link, and then we are going to have to redirect them to the default Google log in page.

**Comment by tskir** [comment]
While I agree there isn't _much_ to design, this dropdown menu is not present at all in our mockups. Also, it'll have to look different for the cases where the user is logged in vs. logged out.

You're welcome to go ahead with the implementation though. If needed, I'll be able to add my comments directly to the PR

**Comment by joj0s** [comment]
I agree, I will add that the dropdown menu to Figma then

**Comment by joj0s** [comment]
It's done, feel free to take a look and tell me your thoughts https://www.figma.com/file/pd5DHJSsldVtJcbp4RvkPb/GSoC-Trait-Mapping-App?node-id=0%3A1

**Comment by tskir** [comment]
Yeah, so this is why I wanted to have a look at it first. Since the popup window only really includes one or two elements (and we don't have immediate plans to add more things to it), it seems not very fitting into the whole current concept of the user interface. Could we maybe just include that directly into the top panel? Something like:
* Not logged in. [Log in with Google](https://example.com)
* Logged in as **user1**. [Log out](https://example.com)

Could you try that in the mockup to see how it would look like?

**Comment by joj0s** [comment]
I have updated the prototype. Feel free to share your opinion

**Comment by tskir** [comment]
Now, this looks great! Going from here, I think this can be simplified even further:
* For the "not logged in state", we can remove both the user icon and the "Not Logged In" text, leaving just the “Log in” button
* For the "logged in" state, we can remove the "Logged in as", leaving just the user icon + user name + the “Log out” button

**Comment by joj0s** [comment]
Agreed, I'll add that to the Figma prototype as well.
