### ISSUE TITLE
Configure timezones 

### ISSUE THREAD

**Issue by joj0s** [EBIvariation/trait-curation#57]
We need to configure the server's timezone and also translate datetime objects to the end user's local timezone

**Comment by joj0s** [comment]
@tskir I have been working on this today. Turns out the latter part is really difficult because there is no easy way of getting a user's local timezone. The only way I have found is to make calls to an external API in order to get the IP origin's time zone but I'm not sure we want to go that route. So what I would suggest is that we set the server's time zone to the EBI location's timezone, and only display dates without hours and minutes to avoid confusion

**Comment by tskir** [comment]
> Turns out the latter part is really difficult because there is no easy way of getting a user's local timezone

Damn it, W3C, you had one job...

> The only way I have found is to make calls to an external API in order to get the IP origin's time zone but I'm not sure we want to go that route

Yes, this is not great. I had only tangential experience with GeoIP databases, but they are either far from being accurate. Besides, a user might be using a VPN, which is fairly common nowadays. So yes, we won't go this way.

> So what I would suggest is that we set the server's time zone to the EBI location's timezone, and only display dates without hours and minutes to avoid confusion

This is an acceptable solution, but if we go with it, I'd like to modify it:
* It's better to just always use UTC rather than a specific “primary” timezone. (Coincidentally, half of the year EBI's timezone _is_ UTC).
* We still want to display hours and minutes in addition to the date for better granularity. We just need to make this explicit by specifying the timezone, e.g.: "Last modified by user1 on 12 Jul 2020, 14:05 UTC"

**Comment by tskir** [comment]
Another approach which I was able to find out is based on JavaScript. Detection of a local timezone this way should be much more reliable than GeoIP-based approaches. So maybe it's also worth considering: https://github.com/adamcharnock/django-tz-detect

**Comment by joj0s** [comment]
So the best approach I've found for this is the following:
First of all we use UTC for the server. Then, we pass a UTC ISO formatted date object to the client and we convert with JavaScript to local time. This is considered the best because it turns out that even though JS doesn't have many problems converting dates to local dates, it does have a hard time figuring out the browser's time zone accurately.

**Comment by joj0s** [comment]
Also whatever we decide, since this issue doesn't require many changes to the codebase should I integrate to another PR like the currently #66 or an upcoming one like the one that contains the trait history section?

**Comment by joj0s** [comment]
A downside of this is what we can't output the date directly into the HTML, and we would need to use something like that for every element that contains a date to do it:
```
<p onload=displayDate( this, "{{mapping.timestamp}}" )> </p>

<script>
function displayDate(element, timestamp) {
formattedDate = format(timestamp);
element.innerHTML = formattedDate
}
```

**Comment by tskir** [comment]
> So the best approach I've found for this is the following

This sounds great, let's implement it.

> Also whatever we decide, since this issue doesn't require many changes to the codebase should I integrate it in another PR like the currently open #66 or an upcoming one like the one that contains the trait history section?

Sure, you can include this change in any of the upcoming PRs.

> A downside of this is what we can't output the date directly into the HTML, and we would need to use something like that for every element that contains a date to do it

Meh. Comprared to downsides of alternatives (like querying the GeoIP databases), I think this issue is tiny. And overall the approach seems very sensible.
