### ISSUE TITLE
Determine a starting UI prototype

### ISSUE THREAD

**Issue by joj0s** [EBIvariation/trait-curation#6]
In my proposal, I created an example UI design in Figma: https://www.figma.com/file/pd5DHJSsldVtJcbp4RvkPb/GSoC-Trait-Mapping-App?node-id=0%3A1

It would be helpful to continue improving it and getting comments on it, so that we have a clear idea of how the app will look and feel as development starts

**Comment by tskir** [comment]
I've reviewed the existing UI prototype again and left some comments on Figma with details. Here is the summary of the proposed changes:

## Overall
* Merge the existing 5 pages into just 2 distint ones — the main page and the single mapping page. This should both simplify the development & improve user experience.
  + "Browse/Review/Curate mappings" → Main page (all traits)
  + "Mapping page" and "Mapping history" → Single trait page
* Try to make the design more compact.

## Main page
* Remove "Configure Datasources"
* Add more columns to the table (ontology label, in EFO, not obsolete)
* Do not implement pagination

## Single trait page
* Make comments and history actions interspersed

Please let me know if you have any questions. Once you introduce the changes, we can go through another one or two iterations of UI review before proceeding with implementation.

**Comment by joj0s** [comment]
Some follow-ups about the comments you left:

- By "ontology labels", do you mean (EFO, MONDO, etc?)

- I'm also not sure how you envision the comment/history section, do you mean something like this?:

> **UserA mapped trait_A to ontology_A** 

> **UserA commented: ** I think ontologyA would be best to map...

**Comment by joj0s** [comment]
Also I suggest that instead of adding a new column in the table for obsolete terms, we could add it as another status

**Comment by tskir** [comment]
@joj0s 

> By "ontology labels", do you mean (EFO, MONDO, etc?)

Not quite. Sorry, the terminology can be confusing.
* **Trait name,** or **source name,** is how trait (a disease) is named in the source database, in our case ClinVar. For example, _Lou-Gehrigs Disease_
* **Ontology term** is the actual record in the ontology. It's referred to by the **ontology term URI,** for example _http://www.ebi.ac.uk/efo/EFO_0000253_
* **Ontology label** is how the ontology term is named (labeled) in the ontology. For example, the above term is named _amyotrophic lateral sclerosis._ Essentially, this is the standardised name, chosen from the full list of possible names by the ontology maintainers.

**Comment by tskir** [comment]
> I'm also not sure how you envision the comment/history section, do you mean something like this?:

Yes. For additional examples, just look at this very discussion page. It includes both comments and actions. For examplke, "joj0s added this to In progress in Project Progress 4 days ago" is an action displayed inline with our comments.

**Comment by tskir** [comment]
> Also I suggest that instead of adding a new column in the table for obsolete terms, we could add it as another status

Yes, this is also an acceptable option. I suppose this is not crucially important for the UI prototype. However, we really should discuss and finalise the list of traits and possible transitions between them. For that purpose, I've created an additional issue: https://github.com/EBIvariation/trait-curation/issues/7

**Comment by tskir** [comment]
Also, I saw that you introduced some changes to the UI prototype already. Please let me know once you're done, and I'll review it again

**Comment by joj0s** [comment]
I have gone through all the changes you mentioned. In particular:
- I made the whole UI more compact in order to fit more information
- I added a label column to the table. As I discussed in the issues regarding the model, I suggested that "obsolete" and "deleted" become different possible status fields for a trait, so I merged them into the "status" column. If you think this approach is not optimal let me know so we can change it.
- I added the status label to the mapping page as well 
- I added an interspersed comment/history section to the mapping page
- I added a "other actions" section to the mapping page to suggest existing terms or open PRs for new ones.

**Comment by tskir** [comment]
@joj0s Great! I think we're really going in the right direction here. You were right that changing & discussing mockups in Figma is much easier than working on the live prototype. I added some more comments:
* Pinning "Export" buttons to the top panel and synchronising this panel between the screens
* Replacing repeated "Go to mapping page" buttons with trait names being links
* Clarifying mapping/trait terminology
* Clarify UI for creating new terms and importing terms from other ontologies
* Adding more fields into the trait page
* Minor design comments (element proximity, comment box on the trait page)

After we finalise discussions in #7 about the statuses, we might have to tweak the UI some more. But the changes I describe above should be applicable either way.

**Comment by joj0s** [comment]
I am currently addressing some design and UX improvements, but #7 is indeed kind of a roadblock right now, as all pages depend on the different status values we can have. So I think we need to prioritize that.

**Comment by joj0s** [comment]
I also have a question about exporting in TSV or other formats. Are we going to need to export anything other than list of traits? Because if so, we would only need that button in the page for trait query results, correct?

**Comment by tskir** [comment]
> I am currently addressing some design and UX improvements, but #7 is indeed kind of a roadblock right now, as all pages depend on the different status values we can have. So I think we need to prioritize that.

I agree. I left some comments in the Google doc for #7 and #8. In the meanwhile, I'll review the UI mockup again to see if there are some changes which are not dependent on statuses which we can make in the meanwhile.

> I also have a question about exporting in TSV or other formats. Are we going to need to export anything other than list of traits? Because if so, we would only need that button in the page for trait query results, correct?

Yes. Essentially, we need to be able to export whatever state of the "list of traits" page we can display, in the TSV form. So the button should only be on that page.

**Comment by joj0s** [comment]
I have finished another UI update. This one was quite a large one. In particular

- As per your suggestion, I split up the search and results page
- Added a home page showing traits that require curation
- Updated the navbar links
- Added a linked records field to the results table as you mentioned
- In the trait detail page, I moved the review section completely to the sidebar. I also added status fields for the master and the term status, and added an ontology label. 
- Added a comment box to the history section
- Added the ontology labels to the suggested terms section

**Comment by tskir** [comment]
@joj0s Thanks! Everything looks very good, and in this ticket we are also undoubtedly moving in the right direction. The only problem is that it looks like confusion happened somewhere along the way, as I did _not_ suggest to split the pages for search and results :) Could you clarify which of my comments/suggestions are you referring to, so that I could know what the problem was with my wording?

Anyway, what you currently have looks very good. I will shortly go through the Figma document for the third and probably final iteration of reviews.

**Comment by joj0s** [comment]
Regarding moving the search page, I was sure I heard you suggest it during last Friday's call so I wrote that down. I guess it was a misunderstanding on my part then, should i merge them back?

**Comment by tskir** [comment]
> Regarding moving the search page, I was sure I heard you suggest it during last Friday's call so I wrote that down. I guess it was a misunderstanding on my part then, should i merge them back?

I see. Yes, probably a miscommunication happened, sorry about that. I guess we can adopt a rule of writing down all major decisions inside their corresponding issues to avoid that in the future. However, splitting those pages wasn't in vain—looking at it helped me design an improved approach which I describe below.

I have just completed the third iteration of reviews, and yes, I think we should merge the screens 1–3 into a single page, with this sequence of elements, listed by row:
* **Top row:** navbar (unchanged)
* **Text filter row**: left-aligned filter box ("Search trait names, ontologies or labels..."); filter button; export buttons
* **Status filter row**. It should consist of several clickable buttons, arranged left to right, which represent all trait (master) statuses present in the database. Something like, "Filter by status:   All [1430]   Awaiting review [51]   Deleted [4]   Obsolete[11]   Unmapped [512]   Current [852]". The styling of buttons can be something like you currently have on the very first screen.
* **Trait table**: the usual table we currently have on the third screen.

This united screen will be the main page, by default showing all traits with text filter empty.

Also some other minor comments:
* Main page
  + Making the trait table more compact and adding more placeholder traits
  + Styling trait names elements as links (blue and underlined)
* Single trait page
  + Considering UI support for very long trait names/labels
  + Styling CURIE text as link
  + Making purpose of the "Suggest an existing term" text field more clear
  + Adding fields for creation of a new term

**Comment by joj0s** [comment]
> Adding fields for creation of a new term
Aiming at saving some space, I was thinking of making that a pop-up form, something like those modal forms for logging in on various sites. What do you think? 

Other than that, I will work on your suggestions. Just to clarify, by doing what you said, we would have only one link in the navbar for the home page, right?

**Comment by tskir** [comment]
> Aiming at saving some space, I was thinking of making that a pop-up form, something like those modal forms for logging in on various sites. What do you think?

Yes, that would also be fine. A possible problem I see with the modal form is that it might be more cumbersome to implement. And also, given that most everyone have at least FullHD screens these days, I don't feel we need to be that concerned about saving space. Anyway, for this particular question implement it in whichever way is more convenient for you.

> Just to clarify, by doing what you said, we would have only one link in the navbar for the home page, right?

Yes, looks like it. In the future we will add a page to prepare a PR for EFO, and it will also be in the navbar. But this will be done separately and not in this ticket.

**Comment by joj0s** [comment]
I have gone through your reviews, check the prototype out and tell me your thoughts!

One question though on making the trait table more compact. Do you mean making the columns more compact by moving them closer together? Or making the rows closer to each other?

**Comment by tskir** [comment]
> One question though on making the trait table more compact. Do you mean making the columns more compact by moving them closer together? Or making the rows closer to each other?

Oh, right, sorry for not being specific here. The columns are fine, they are allowed to (and even _should_) take 100% of the width to accommodate for long trait/label names. What I mean by more compact is making the rows closer. What I'm aiming for is something comparable to Google Sheets default rows density (or maybe a little less compact than that).

> I have gone through your reviews, check the prototype out and tell me your thoughts!

I have finished the fourth iteration of review, and I think it's going to the final one. What you now have in Figma looks fantastic! I left some really minor comments about styling. Actually, at this point, fixing them in the Figma mockup is optional — all of them are really fine details and they can be tweaked directly in the CSS when we have the actual implementation. So unless you have any further questions about the UI and its implementation, we can close this issue.

**Comment by joj0s** [comment]
I think I have a pretty good idea of the expected UI now. I will close the issue and if any further questions arise, I will post them in a separate issue or in the Slack channel
