### ISSUE TITLE
Set up a proper deployment environment

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#61]
We're getting into some limitations of free Heroku plan (#59), so should expedite work on setting up a proper deployment environment. I'll look into this.

**Comment by tskir** [comment]
@joj0s I intend to write a request to the appropriate department at EBI to discuss this. Before I do this, I'd like to hear from you what you would require from such an environment. I know we already discussed this in an older ticket, but things might have changed in the course of development. I can see two options here, let me know which one you prefer, or maybe there are others.

Option 1 would be to essentially compile instructions for manual deployment, assuming a Linux (Ubuntu?) OS. It would include installing the necessary packages, setting up and starting Postgres/Redis/Celery, and configuring the app to use those. I assume you already have some sort of a local deployment for testing, so assuming we get access to such a server, it shouldn't be too difficult to set up..

Option 2 is to put everything into Docker. I know some smaller, self-contained EBI services use them, for example OLS itself, see: https://github.com/EBISPOT/OLS-docker. This cab also be used both for production, and for local deployment for testing.

A whole separate thing is about linking this to the GitHub repo and automatically building the PRs like Heroku does. We'll discuss this separately. As was mentioned during the previous discussion, EBI has a GitLab instance which we should be able to set up to do this. I'll also handle this.

**Comment by joj0s** [comment]
I don't have much experience setting up Docker, so yeah I think Option 1 sounds the best. Since I use Debian based Linux distros both locally and in my university, Ubuntu would be the easiest for me to set up.

**Comment by tskir** [comment]
OK, so for now let's go with the first option. I will write an email shortly to the appropriate EBI department and will put you in copy

**Comment by tskir** [comment]
Submitted a request to Embassy Cloud. Requested a total quota of 8 CPUs, 32 GB RAM, 2 floating IPs, 512 GB for image and volume storage, for a total duration of 6 months (for now).

@joj0s While we're waiting for the request to be processed, here's the link to the Embassy Cloud documentation:
http://docs.embassy.ebi.ac.uk/userguide/Embassy_About.html

You will need only sections 1 and 2, as we're not getting involved with Kubernetes at this stage.

**Comment by tskir** [comment]
I now have access to the Embassy cloud as a tenancy admin. So far I have set up the initial things, like project-wide settings, and created some test instances. I also wrote docs on this part of the configuration: https://github.com/EBIvariation/trait-curation/blob/master/docs/embassy-deployment.md

What's remaining is to configure networks and port forwardng.

**Comment by tskir** [comment]
Everything's done, docs are here https://github.com/EBIvariation/trait-curation/blob/master/docs/embassy-deployment.md
