### ISSUE TITLE
Set up deployment in the Embassy cloud

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#69]
Embassy instances are just self-managed Ubuntu machines, for which we have root access. The goal of this issue is to deploy the app in that infrastructure, and its end result should be a PR adding documentation on how to do that (including installation of all necessary packages and the actual deployment).

**Comment by joj0s** [comment]
Since only SSH and ICMP are enabled, I think the best way to approach this is to set up the server from scatch in a Ubuntu Server VM of mine, and when I verify that everything works and I have created instructions for it, then we can proceed with the actual deployment.

**Comment by joj0s** [comment]
Also, since Heroku hasn't shown any major problems during development, should I use development or production settings for this deployment?

**Comment by tskir** [comment]
> Since only SSH and ICMP are enabled, I think the best way to approach this is to set up the server from scatch in a Ubuntu Server VM of mine, and when I verify that everything works and I have created instructions for it, then we can proceed with the actual deployment.

Yes, this sounds like a good approach. Although note that access being limited to SSH and ICMP is not a conceptual limitation, those are just the ports I enabled so far. If you know in advance which ports the app will need, you can tell me and I'll open them right away.

> Also, since Heroku hasn't shown any major problems during development, should I use development or production settings for this deployment?

I think we want to start with deployment settings for now. The app is still under development, so some crashes & bugs are expected, and in this case we want the stack traces etc. to be displayed

**Comment by joj0s** [comment]
@tskir Whenever possible, I'ld like ports 80 and 8000 open. Port 8000 is just for testing the development server, it can be closed again after deployment is done.

**Comment by tskir** [comment]
@joj0s This is now done. I've opened ports 80 (HTTP), 443 (HTTPS) and 8000 (dev server). Also updated the instructions here: https://github.com/EBIvariation/trait-curation/blob/master/docs/embassy-deployment.md

**Comment by joj0s** [comment]
@tskir Is there any domain name associated with the Embassy instances? I am asking because I get this error when I try to set up the callback URI for Google authentication: 
![image](https://user-images.githubusercontent.com/36301625/91426456-395da200-e865-11ea-87bf-d3fb07782981.png)

**Comment by joj0s** [comment]
So here's an update on the current state of Embassy deployments:

Deployment on the second machine (`trait-curation-2`, http://45.86.170.233) is done. Everything works except for anything that requires external API interaction (Google authentication, Sheets and GitHub API) until the domain issue is resolved. 

Reminder that we decided we will use trait-curation-2 as a development deployment machine since that limitations of the free Heroku plan are starting to become a major problem. When the domain issue is resolved, I will deploy PR #85 in order to be reviewed since I wasn't able to make Sheets authentication work on Heroku due to a `credentials.json` file required by Google to be present on the server.

As for trait-curation-1, our production machine, my plan is to have a domain for it as well, obtain a SSL certificate and then deploy it as well.

**Comment by tskir** [comment]
@joj0s I believe Embassy does not provide any domain names by default. I have associated two public domains using DuckDNS:
* http://trait-curation-1.duckdns.org   •   45.86.170.232
* http://trait-curation-2.duckdns.org   •   45.86.170.233

Although http://45.86.170.233 is working, http://trait-curation-2.duckdns.org is not — maybe some additional web server configuration is required to work with the domain?

**Comment by joj0s** [comment]
> Although http://45.86.170.233 is working, http://trait-curation-2.duckdns.org is not — maybe some additional web server configuration is required to work with the domain?

Yes, I will have to register this domain in the NginX configuration in order for it to work, I will do that right now.

**Comment by joj0s** [comment]
Although I am pretty sure that until we get a correctly registered domain name, we can't use HTTPS for they deployment. In our case it won't be that big of a deal for now, since we don't deal with any sensitive user data directly, but it is something to bear in mind.

**Comment by tskir** [comment]
I don't think HTTPS should be considered a priority for now, it is not necessary for our most basic use case. I've created a follow up issue for some time in the future: #88.

Since the deployment appears to work, could you submit a PR with documentation updates about how to deploy on Embassy?

**Comment by joj0s** [comment]
> Since the deployment appears to work, could you submit a PR with documentation updates about how to deploy on Embassy?

WIll do, although first I need to create a file to store database credentials and other settings that should not be hardcoded and commit them so that I don't have to change settings with every `git pull`, and also test task scheduling on Embassy.

**Comment by joj0s** [comment]
So regarding the settings.py file and the external config file to read the credentials, there are two problems we need to solve here: Managing the credentials, and managing the different project settings depending on the environment. 

As mentioned, we can create a yaml file in a private repo to store our credentials. 

Now, regarding the different settings:
- When working in a **local development** environment, we want to use `DEBUG=True` and we want to use SQLite as our database.
- When working in a **deployed development** environment, we want to use `DEBUG=True` and we want to use our configured PostgreSQL as our database. 
- When working in a **deployed production** environment we want to use `DEBUG=False` and we want to use our configured PostgreSQL as our database.

To avoid overwriting over stuff, Django recommends using different settings.py files depending on the environment. In my opinion, the best approach is the one described [here](https://stackoverflow.com/a/34891731). We can have a `settings_localdev.py` and `settings_dev.py` file  that overrides the mentioned settings, and we can have a single environment variable called `DJANGO_ENV` or something like that, to control what settings we want to use in each environment. How does that sound?

**Comment by tskir** [comment]
> As mentioned, we can create a yaml file in a private repo to store our credentials.

Indeed. I have now created this repo and granted you write access.

The approach you described for managing different environments sounds great! I can't think of a better option.
