### ISSUE TITLE
Design a page for submitting feedback to EFO maintainers

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#72]
It has to list all traits which are currently:
* Mapped to a term which status is “needs import” or “needs creation”, _and_
* Have been reviewed.

(This would presumably reuse the view functionality of the main page.)

The page should also contain the following fields which are editable, but already pre-filled with information:
* Link of the GitHub repository to which the issue will be submitted
* Issue title
* Issue body contents

Finally, there should be a “Submit issue” button. The functionality of that button will be described in a separate issue for implementation.

**Comment by tskir** [comment]
Corresponding implementation issue: #73

**Comment by joj0s** [comment]
So just to clarify, both the 'needs_import' and 'needs_creation' terms are submitted together and not separately?

**Comment by joj0s** [comment]
Also, would it be of any use to provide the user the ability to choose specific mappings to submit in separate batches, or is that unnecessary?

**Comment by tskir** [comment]
> So just to clarify, both the 'needs_import' and 'needs_creation' terms are submitted together and not separately?

They are submitted together. Also note that the "import" traits are submitted in a spreadsheet with their various attributes. I'm not sure what would be the best way to do that in the app. Maybe we'll have to first use Google Sheets API to create a spreadsheet, and then include a link to that in the issue submitted via the GitHub API. I hear that both Google Docs/Sheets and GitHub APIs are both relatively straightforward, so hopefully we'll be able to implement that eventually.

By the way, here's a link to an example issue which we submit, it might be helpful: https://github.com/EBISPOT/efo/issues/814

> Also, would it be of any use to provide the user the ability to choose specific mappings to submit in separate batches, or is that unnecessary? (By that I mean choosing for example 10 out of 20 mappings that are awaiting import, possibly because someone would want to submit them at different GitHub repos?)

At this point it's not necessary. In our use case, we will only submit to EFO, and always all terms at once.

**Comment by joj0s** [comment]
So first of all, that example issue is indeed really helpful, thanks.

 Now, since the terms to be imported are submitted in a spreadsheet, how would be submit the terms that need to be created? As free text in the same GitHub issue that contains spreadsheet link perhaps?

**Comment by tskir** [comment]
> Now, since the terms to be imported are submitted in a spreadsheet, how would be submit the terms that need to be created? As free text in the same GitHub issue that contains spreadsheet link perhaps?

Yes, currently this is exactly the way this is addressed. But since we are generating a spreadsheet anyway, maybe it would be better to just add another sheet for "new" terms, which would have three columns: name, description, cross-refs. This might be easier to read than pasting that directly into the issue text, especially if we submit a large number of traits at once. Anyway, either of the approaches would be acceptable for now.

**Comment by joj0s** [comment]
i have created a prototype for this page. You can see it here https://www.figma.com/file/pd5DHJSsldVtJcbp4RvkPb/GSoC-Trait-Mapping-App?node-id=286%3A31 and leave your comments as always.

**Comment by tskir** [comment]
Looks great! BTW, I welcome the change of “Browse traits” → “Traits” and “External datasources” → “Sources”, looks more cool & succinct.

The only problem that I see with the current design is that, in the page base state, the “Create issue” button looks like it would **immediately** create an issue without asking anything further from the user. This is exacerbated by the fact that it has a GitHub icon on it. So if I wasn't familiar with the app, I would be hesitant to press it, because it seems like it would perform a serious and irreversible action straight away. Some things we can do about this:
* Add an ellipsis to the text, to make it “Create issue...” — a universal sign in UI design that the action will not be performed immediately;
* Rename it to something like “Start feedback submission process” (a tad unwieldy though);
* Remove it entirely and just always display the submission fields. After all, if someone already opened this page, it's highly likely that they want to proceed with the submission.

Feel free to try any of those options. Also, as a minor detail, I would probably combine the "import" and "create" term suggestions into a single spreadsheet, just use the different sheets. So that would leave only one link in the issue body.

**Comment by joj0s** [comment]
> I would probably combine the "import" and "create" term suggestions into a single spreadsheet, just use the different sheets. So that would leave only one link in the issue body.

Agreed, that sounds better.

> Remove it entirely and just always display the submission fields. After all, if someone already opened this page, it's highly likely that they want to proceed with the submission.

I think this would be the best option yes. I thought about the form hiding the table with the mappings that need to be submitted but indeed that is not the main action of the page.
