### ISSUE TITLE
Describe and discuss the data model

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#8]
It was mentioned during the last call that we should have a shared Google doc for discussing and finalising the data model. Could you please create this doc and link it from here?

**Comment by joj0s** [comment]
Here it is. https://docs.google.com/document/d/1iunypcRGtlxPc_uwhjKnMv8tD67dHOEPaOQMxHSL96U/edit?usp=sharing

**Comment by tskir** [comment]
@joj0s Great! I have reviewed it and left some comments. However, the final data model will heavily depend on the decisions which we will make in #7, so this will need to be finalised first.

**Comment by tskir** [comment]
I've done another review of data model, which I think is very nearly completed at this point, and added some comments and considerations, most notably on statuses (#7).

**Comment by tskir** [comment]
Third and probably final iteration of data model review is done. I'm really happy with how everything is shaping up here. Once we close all comments in the document, the final thing to do would be to transfer the contents of that Google Doc into a Markdown documentation page directly in this repo. Google Doc was useful for discussions and comments, but it will be important to have a permanent record

**Comment by tskir** [comment]
I have looked at the document again and I'm happy to approve it. No further changes to data model or statuses will be necessary at this stage. Great work!

The remaining actions for this ticket is a PR and for #7, a Mermaid diagram
