### ISSUE TITLE
Create a REST API to access the app's data

### ISSUE THREAD

**Issue by joj0s** [EBIvariation/trait-curation#80]

**Comment by joj0s** [comment]
Things to consider for the API:
- What models and fields we want to expose
- What actions we want to allow (I assume read only access)
- Use pagination or not?
- What representation to use for foreign fields (Hyperlinks or nested objects)

**Comment by joj0s** [comment]
After discussion in the weekly call, the following decisions have been made regarding the API:
- We will only expose the `traits` endpoint, which includes a trait name and information, and its current mapping and status.
- The API will be read only for everyone
- We will use pagination
- Since there are limited fields, we will use nesting to represent foreign key relationships such as a trait's current mapping

@tcezard I would like your confirmation on the above, plus any suggested further discussions to be made about the API design.

**Comment by tskir** [comment]
I agree with the decision summary in the comment above, although I don't think implementing the API right now is a priority. This is not necessary for our core use case (which I've designated as 1.0 milestone), so we can get back to this after that one is completed

**Comment by joj0s** [comment]
> I agree with the decision summary in the comment above, although I don't think implementing the API right now is a priority. This is not necessary for our core use case (which I've designated as 1.0 milestone), so we can get back to this after that one is completed

Well, I did create it based on the specifications above and it is ready to be used, I was just waiting on confirmation of the above before submitting a PR. In the discussions with Tim, we suggested that it is essentially a better version of the 'Export to TSV' function so it would be important to have at an early stage.

**Comment by tskir** [comment]
Ah, I see. If the API is already implemented, then that's great, we can use it in version 1.0 already
