### ISSUE TITLE
Implement the 'data sources' page

### ISSUE THREAD

**Issue by joj0s** [EBIvariation/trait-curation#83]
Implementation of the page designed in issue #32.

**Comment by joj0s** [comment]
This page included progress bars for UI feedback regarding every import. Since ClinVar imports involve downloading the data from an external source, the progress bar should display the download progress. However, the only way to do that is to move the download code from [clinvar.py](https://github.com/EBIvariation/trait-curation/blob/532ef37e694fb401f32117b456881daba3fef81f/traitcuration/traits/datasources/clinvar.py#L40) to [tasks.py](https://github.com/EBIvariation/trait-curation/blob/master/traitcuration/traits/tasks.py). Do we mind that? The code in tasks.py then would look something like this:
<details>
  <summary>Running clinvar in tasks.py</summary>
  
  ```python
@shared_task(bind=True)
def import_clinvar():
    progress_recorder = ProgressRecorder(self)
    try:
        with open(file_name, "wb") as f:
            logger.info("Downloading ClinVar data...")
            response = requests.get(URL, allow_redirects=True, stream=True)
            total_length = response.headers.get('content-length')
            total_length = int(total_length)
            downloaded_length = 0
            for data in response.iter_content(chunk_size=4096):
                downloaded_length += len(data)
                f.write(data)
                done = int(50 * dl / total_length)
                progress_recorder.set_progress(downloaded_length, total_length)
            traits_dict = clinvar.parse_trait_names_and_source_records()
            clinvar.store_data(traits_dict)
    except Exception:
        track = traceback.format_exc()
        logger.error(track)
        return
```
</details>

**Comment by joj0s** [comment]
@tcezard Only one thing remaining for this page. As we decided, for issue #34, we are going to use the Django Admin to define scheduled tasks. 

The problem is that since we let the admin choose the name of those periodic tasks, we have no way of reading from the database when the next scheduled import is. So we can either skip the 'Next scheduled import' section, or we can somehow enforce admins on choosing a specific name for the periodic tasks, so I can hardcode that in the app?

**Comment by tskir** [comment]
> However, the only way to do that is to move the download code from clinvar.py to tasks.py. Do we mind that?

I don't mind, this looks fine. Having a progress bar for a very long operation is important.

> Only one thing remaining for this page. As we decided, for issue #34, we are going to use the Django Admin to define scheduled tasks.

The problem is that since we let the admin choose the name of those periodic tasks, we have no way of reading from the database when the next scheduled import is. So we can either skip the 'Next scheduled import' section, or we can somehow enforce admins on choosing a specific name for the periodic tasks, so I can hardcode that in the app?

We can discuss this further in #34. In short, since tasks configurable by admins bring about this complexity about names, persistence etc., I think at this point we whould just hardcode the names and intervals in `settings.py`. Given that those values will be changed very rarely if ever, this seems to me like a reasonable solution for this stage of the project.

I will review the associated PR shortly.

**Comment by joj0s** [comment]
> We can discuss this further in #34. In short, since tasks configurable by admins bring about this complexity about names, persistence etc., I think at this point we should just hardcode the names and intervals in settings.py. Given that those values will be changed very rarely if ever, this seems to me like a reasonable solution for this stage of the project.

So since this discussion is outside the immediate scope of the issue, PR #87 does not include any sort of task scheduling, and I removed the 'Next scheduled import' section from the page. I can implement the hardcoding task scheduling in the next upcoming PR for issue #34.

Also, regarding this PR, it is deployed on Heroku so you can check it there. It will probably be the last PR that is able to function on Heroku, since we are going to need to run a background scheduler for task automation and free Heroku only allows two workers running at the same time.

**Comment by tskir** [comment]
> So since this discussion is outside the immediate scope of the issue, PR #87 does not include any sort of task scheduling, and I removed the 'Next scheduled import' section from the page. I can implement the hardcoding task scheduling in the next upcoming PR for issue #34.

OK, makes sense to me.

> Also, regarding this PR, it is deployed on Heroku so you can check it there. It will probably be the last PR that is able to function on Heroku, since we are going to need to run a background scheduler for task automation and free Heroku only allows two workers running at the same time.

OK. Only when you submit PR for #34, please ensure that you add instructions for deploying any given branch in Embassy
