### ISSUE TITLE
Remove the autogenerated secret key from settings.py

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#86]
The `traitcuration/settings.py` file [contains](https://github.com/EBIvariation/trait-curation/blob/c1d467472442758d28aea5983c55c118a1b02e56/traitcuration/settings.py#L24) an automatically generated secret key. While we don't use it anywhere, it should still be removed to avoid confusion.

**Comment by joj0s** [comment]
This setting is being used by Django for cryptography purposes so it shouldn't be completely removed, but it should be re-generated and kept in a separate uncommitted file, along with the database credentials in the deployment machines.

**Comment by tskir** [comment]
I realise we cannot and should not remove this field completely. What I mean is that this key should be blanked in the repository, and the deployment instructions should mention that it will have to be re-generated prior to deployment
